import type { Service } from "@/lib/types";

export const categories = ["Desain", "Marketing", "Teknologi", "Konten"] as const;

export const seedServices: Service[] = [
  {
    id: "ui-ux-kit",
    title: "UI/UX Design Kit Mobile",
    provider: "StudioPixel",
    avatar: "UX",
    avatarTone: "bg-indigo-100 text-indigo-700",
    category: "Desain",
    price: 149000,
    rating: 4.8,
    description: "Template UI/UX lengkap untuk aplikasi e-commerce. Berisi 50+ halaman siap pakai di Figma.",
    iconName: "layers",
    previewLabel: "Pratinjau Produk Digital",
    owner: "other",
    createdAt: "2026-07-17",
    reviews: [
      {
        id: "ui-positive",
        sentiment: "positive",
        author: "Budi",
        text: "Komponennya rapi banget dan gampang di-custom. Hemat waktu kerja!",
        createdAt: "2026-07-18T09:10:00.000Z",
      },
      {
        id: "ui-negative",
        sentiment: "negative",
        author: "Siti",
        text: "Sayangnya belum ada dark mode, semoga nanti di-update.",
        createdAt: "2026-07-17T16:20:00.000Z",
      },
      {
        id: "ui-positive-2",
        sentiment: "positive",
        author: "Niko",
        text: "Struktur filenya jelas dan dokumentasi komponennya membantu.",
        createdAt: "2026-07-16T13:45:00.000Z",
      },
    ],
  },
  {
    id: "seo-instan",
    title: "Jasa SEO Instan 24 Jam",
    provider: "KlikSukses",
    avatar: "SE",
    avatarTone: "bg-amber-100 text-amber-700",
    category: "Marketing",
    price: 450000,
    rating: 2.3,
    description: "Menaikkan ranking website Anda ke halaman pertama Google hanya dalam waktu 1 hari garansi.",
    iconName: "trending-up",
    previewLabel: "Pratinjau Jasa Digital",
    owner: "other",
    createdAt: "2026-07-16",
    reviews: [
      {
        id: "seo-positive",
        sentiment: "positive",
        author: "Andi",
        text: "Respon penjualnya cepat sekali.",
        createdAt: "2026-07-18T07:30:00.000Z",
      },
      {
        id: "seo-negative",
        sentiment: "negative",
        author: "Rian",
        text: "Malah kena penalti Google karena pake teknik spam. Tidak recommended.",
        createdAt: "2026-07-18T10:05:00.000Z",
      },
      {
        id: "seo-negative-2",
        sentiment: "negative",
        author: "Tama",
        text: "Laporannya tipis dan tidak menjelaskan perubahan yang dikerjakan.",
        createdAt: "2026-07-17T11:00:00.000Z",
      },
    ],
  },
  {
    id: "landing-copy",
    title: "Copywriting Landing Page",
    provider: "NaraWords",
    avatar: "NW",
    avatarTone: "bg-cyan-100 text-cyan-700",
    category: "Konten",
    price: 275000,
    rating: 4.5,
    description: "Paket headline, struktur penawaran, dan CTA untuk landing page produk digital.",
    iconName: "pen-line",
    previewLabel: "Pratinjau Konten",
    owner: "me",
    createdAt: "2026-07-15",
    reviews: [
      {
        id: "copy-positive",
        sentiment: "positive",
        author: "Maya",
        text: "Brief cepat dipahami dan hasil tulisannya enak dipakai untuk eksperimen iklan.",
        createdAt: "2026-07-18T08:25:00.000Z",
      },
      {
        id: "copy-negative",
        sentiment: "negative",
        author: "Dito",
        text: "Butuh satu revisi ekstra untuk menyesuaikan tone brand kami.",
        createdAt: "2026-07-16T19:05:00.000Z",
      },
      {
        id: "copy-positive-2",
        sentiment: "positive",
        author: "Arum",
        text: "CTA-nya lebih tajam dari draft internal kami.",
        createdAt: "2026-07-18T12:15:00.000Z",
      },
      {
        id: "copy-positive-3",
        sentiment: "positive",
        author: "Gilang",
        text: "Paket cocok untuk validasi cepat sebelum iklan besar.",
        createdAt: "2026-07-17T14:15:00.000Z",
      },
    ],
  },
  {
    id: "automation-audit",
    title: "Audit Otomasi Workflow",
    provider: "FlowOps",
    avatar: "FO",
    avatarTone: "bg-emerald-100 text-emerald-700",
    category: "Teknologi",
    price: 650000,
    rating: 4.7,
    description: "Review proses kerja dan rekomendasi otomasi untuk tim sales, support, atau operasional.",
    iconName: "workflow",
    previewLabel: "Pratinjau Audit",
    owner: "other",
    createdAt: "2026-07-14",
    reviews: [
      {
        id: "flow-positive",
        sentiment: "positive",
        author: "Lina",
        text: "Rekomendasinya praktis dan langsung bisa dijadikan backlog internal.",
        createdAt: "2026-07-18T06:50:00.000Z",
      },
      {
        id: "flow-negative",
        sentiment: "negative",
        author: "Bayu",
        text: "Estimasi setup tool masih terlalu umum untuk tim kecil.",
        createdAt: "2026-07-17T20:10:00.000Z",
      },
      {
        id: "flow-positive-2",
        sentiment: "positive",
        author: "Intan",
        text: "Mapping workflow-nya membantu tim kami melihat bottleneck.",
        createdAt: "2026-07-16T12:40:00.000Z",
      },
    ],
  },
];
